/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/portfolio/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio Kpis */
        get: operations["get_portfolio_kpis_api_portfolio_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/tab-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tab Counts */
        get: operations["get_tab_counts_api_portfolio_tab_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/creatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Creatives Flat */
        get: operations["list_creatives_flat_api_creatives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/creatives/{creative_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Creative */
        get: operations["get_creative_api_creatives__creative_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/creatives/{creative_id}/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeseries */
        get: operations["get_timeseries_api_creatives__creative_id__timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/creatives/{creative_id}/twin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Twin */
        get: operations["get_twin_api_creatives__creative_id__twin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advertisers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Advertisers */
        get: operations["list_advertisers_api_advertisers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advertisers/{advertiser_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Advertiser */
        get: operations["get_advertiser_api_advertisers__advertiser_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advertisers/{advertiser_id}/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campaigns */
        get: operations["list_campaigns_api_advertisers__advertiser_id__campaigns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaign */
        get: operations["get_campaign_api_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/creatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Creatives */
        get: operations["list_creatives_api_campaigns__campaign_id__creatives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_agent_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Advertiser */
        Advertiser: {
            /** Advertiser Id */
            advertiser_id: number;
            /** Advertiser Name */
            advertiser_name: string;
            /** Vertical */
            vertical: string;
            /** Hq Region */
            hq_region: string;
        };
        /** Campaign */
        Campaign: {
            /** Campaign Id */
            campaign_id: number;
            /** Advertiser Id */
            advertiser_id: number;
            /** Advertiser Name */
            advertiser_name: string;
            /** App Name */
            app_name: string;
            /** Vertical */
            vertical: string;
            /** Objective */
            objective: string;
            /** Primary Theme */
            primary_theme: string;
            /** Target Age Segment */
            target_age_segment: string;
            /** Target Os */
            target_os: string;
            /** Countries */
            countries: string;
            /** Country List */
            country_list: string[];
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string;
            /** Daily Budget Usd */
            daily_budget_usd: number;
            /** Kpi Goal */
            kpi_goal: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /** CohortKeys */
        CohortKeys: {
            /** Vertical */
            vertical: string;
            /** Format */
            format: string;
        };
        /**
         * CreativeDetail
         * @description Full creative metadata joined with creative_summary on creative_id.
         *
         *     The shape mirrors every column in creatives.csv plus every column in
         *     creative_summary.csv that isn't already on creatives.csv. Fields beyond
         *     the explicitly named ones flow through via `extra="allow"` so the frontend
         *     can render every metadata column without the schema lagging the data.
         */
        CreativeDetail: {
            /** Creative Id */
            creative_id: number;
            /** Campaign Id */
            campaign_id: number;
            /** Asset File */
            asset_file: string;
            quadrant?: components["schemas"]["Quadrant"] | null;
            saturation?: components["schemas"]["Saturation"] | null;
            /** Health */
            health?: number | null;
            /** Status Band */
            status_band?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** CreativeListItem */
        CreativeListItem: {
            /** Creative Id */
            creative_id: number;
            /** Campaign Id */
            campaign_id: number;
            /** Advertiser Name */
            advertiser_name: string;
            /** Vertical */
            vertical: string;
            /** Format */
            format: string;
            /** Theme */
            theme: string;
            /** Creative Status */
            creative_status?: string | null;
            /** Asset File */
            asset_file: string;
        };
        /**
         * CreativeListResponse
         * @description Paginated wrapper for ``/api/creatives``. Total reflects the count
         *     *after filters but before limit*, so callers can render a
         *     "showing X of Y" footer.
         */
        CreativeListResponse: {
            /** Rows */
            rows: components["schemas"]["CreativeRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit?: number | null;
        };
        /** CreativeRow */
        CreativeRow: {
            /** Creative Id */
            creative_id: number;
            /** Campaign Id */
            campaign_id: number;
            /** Advertiser Name */
            advertiser_name: string;
            /** Headline */
            headline: string;
            /** Vertical */
            vertical: string;
            /** Format */
            format: string;
            /** Status */
            status: string | null;
            /** Status Band */
            status_band: string | null;
            /** Ctr */
            ctr: number;
            /** Cvr */
            cvr: number;
            /** Roas */
            roas: number;
            /** Spend Usd */
            spend_usd: number;
            /** Impressions */
            impressions: number;
            /** Clicks */
            clicks: number;
            /** Conversions */
            conversions: number;
            /** Revenue Usd */
            revenue_usd: number;
            /** Days Active */
            days_active: number;
            /** Health */
            health: number;
            /** Sparkline */
            sparkline: number[];
            /** Fatigue Day */
            fatigue_day?: number | null;
            /** Asset File */
            asset_file: string;
        };
        /** CreativeTimeseries */
        CreativeTimeseries: {
            /** Creative Id */
            creative_id: number;
            /** Points */
            points: components["schemas"]["TimeseriesPoint"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PortfolioKPIs */
        PortfolioKPIs: {
            /** Total Spend Usd */
            total_spend_usd: number;
            /** Total Revenue Usd */
            total_revenue_usd: number;
            /** Roas */
            roas: number;
            /** Ctr */
            ctr: number;
            /** Cvr */
            cvr: number;
            /** Attention Count */
            attention_count: number;
        };
        /**
         * Quadrant
         * @description Diagnostic position of a creative in CTR×CVR space, relative to its
         *     cohort. Cohort = (vertical, format). Percentiles are raw; they will be
         *     Bayesian-shrunk once Q1 ranking ships, so low-sample creatives no longer
         *     distort the picture.
         */
        Quadrant: {
            /** Ctr Percentile */
            ctr_percentile: number | null;
            /** Cvr Percentile */
            cvr_percentile: number | null;
            /** Quadrant Label */
            quadrant_label: string;
            cohort_keys: components["schemas"]["CohortKeys"];
            /** Cohort Size */
            cohort_size: number;
        };
        /**
         * Saturation
         * @description Portfolio-saturation signal: how many creatives in the same advertiser
         *     portfolio share this attribute combo. Triple = (theme, hook_type,
         *     dominant_color); falls back to (theme, hook_type) if the triple cohort is
         *     too sparse (see ``used_triple``).
         */
        Saturation: {
            triple: components["schemas"]["SaturationTriple"];
            /** Used Triple */
            used_triple: boolean;
            /** Cohort Advertiser Size */
            cohort_advertiser_size: number;
            /** Cohort Global Size */
            cohort_global_size: number;
            /** Cohort Avg Ctr */
            cohort_avg_ctr: number;
            /** Cohort Avg Cvr */
            cohort_avg_cvr: number;
            /** This Ctr */
            this_ctr: number;
            /** This Cvr */
            this_cvr: number;
            /** Recommend Consolidate To */
            recommend_consolidate_to?: number | null;
        };
        /** SaturationTriple */
        SaturationTriple: {
            /** Theme */
            theme: string | null;
            /** Hook Type */
            hook_type: string | null;
            /** Dominant Color */
            dominant_color: string | null;
        };
        /** SearchHit */
        SearchHit: {
            /** Creative Id */
            creative_id: number;
            /** Headline */
            headline?: string | null;
            /** Advertiser Name */
            advertiser_name?: string | null;
            /** Vertical */
            vertical?: string | null;
            /** Format */
            format?: string | null;
            /** Status */
            status?: string | null;
            /** Status Band */
            status_band?: string | null;
            /** Health */
            health?: number | null;
            /** Asset File */
            asset_file?: string | null;
            /** Theme */
            theme?: string | null;
            /** Hook Type */
            hook_type?: string | null;
            /** Score */
            score: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
        };
        /** TabCounts */
        TabCounts: {
            /** Scale */
            scale: number;
            /** Watch */
            watch: number;
            /** Rescue */
            rescue: number;
            /** Cut */
            cut: number;
            /** Explore */
            explore: number;
        };
        /** TimeseriesPoint */
        TimeseriesPoint: {
            /** Date */
            date: string;
            /** Impressions */
            impressions: number;
            /** Clicks */
            clicks: number;
            /** Conversions */
            conversions: number;
            /** Spend Usd */
            spend_usd: number;
            /** Revenue Usd */
            revenue_usd: number;
        };
        /** TwinDiff */
        TwinDiff: {
            /** Field */
            field: string;
            /** Source Value */
            source_value: unknown;
            /** Twin Value */
            twin_value: unknown;
            /** Direction */
            direction: string;
            /** Impact */
            impact: string;
        };
        /** TwinSegment */
        TwinSegment: {
            /** Vertical */
            vertical: string;
            /** Format */
            format: string;
        };
        /** TwinSummary */
        TwinSummary: {
            /** Fatigued Id */
            fatigued_id: number;
            /** Winner Id */
            winner_id: number;
            /** Similarity */
            similarity: number;
            segment: components["schemas"]["TwinSegment"];
            /** Diffs */
            diffs: components["schemas"]["TwinDiff"][];
            vision_insight: components["schemas"]["VisionInsight"];
            /**
             * Is Stub
             * @default true
             */
            is_stub: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisionInsight */
        VisionInsight: {
            /** Headline */
            headline: string;
            /** Body */
            body: string;
            /** Confidence */
            confidence: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_portfolio_kpis_api_portfolio_kpis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioKPIs"];
                };
            };
        };
    };
    get_tab_counts_api_portfolio_tab_counts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TabCounts"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_creatives_flat_api_creatives_get: {
        parameters: {
            query?: {
                /** @description scale|watch|rescue|cut|explore */
                tab?: string | null;
                status?: string | null;
                vertical?: string | null;
                format?: string | null;
                sort?: string | null;
                desc?: boolean;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_creative_api_creatives__creative_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                creative_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeseries_api_creatives__creative_id__timeseries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                creative_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeTimeseries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_twin_api_creatives__creative_id__twin_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                creative_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwinSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_advertisers_api_advertisers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Advertiser"][];
                };
            };
        };
    };
    get_advertiser_api_advertisers__advertiser_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                advertiser_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Advertiser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campaigns_api_advertisers__advertiser_id__campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                advertiser_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_api_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_creatives_api_campaigns__campaign_id__creatives_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_agent_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_agent_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
