import Link from "next/link";
import { notFound } from "next/navigation";

import { api } from "@/lib/api";
import { BriefPanel, type BriefField } from "@/components/design/BriefPanel";
import { Lineage } from "@/components/design/Lineage";
import { PredictedLift, type LiftRow } from "@/components/design/PredictedLift";
import { ApplyVariantBar } from "@/components/design/ApplyVariantBar";
import { PreviewChip } from "@/components/design/PreviewChip";
import {
  RenderedVariantSvg,
  type VariantBrief,
} from "@/components/design/RenderedVariantSvg";

export default async function VariantPage(
  props: PageProps<"/creatives/[creativeId]/variant">,
) {
  const { creativeId } = await props.params;
  const id = Number(creativeId);
  if (!Number.isFinite(id)) notFound();

  // The variant-brief endpoint internally calls the same twin lookup, then
  // asks Gemma to write a fresh headline/subhead/CTA + rationale grounded
  // in the source vs. winner attribute diffs. If Gemma is unavailable the
  // backend falls back to a template-generated brief and stamps is_stub
  // true; we use that flag to render the [preview] chip.
  let llmBrief;
  try {
    llmBrief = await api.getVariantBrief(id);
  } catch {
    notFound();
  }

  const [source, winner] = await Promise.all([
    api.getCreative(llmBrief.creative_id),
    api.getCreative(llmBrief.winner_id),
  ]);
  const sourceData = source as unknown as Record<string, number | string | null | undefined>;
  const winnerData = winner as unknown as Record<string, number | string | null | undefined>;

  const brief: VariantBrief = {
    headline: llmBrief.headline,
    subhead: llmBrief.subhead,
    cta: llmBrief.cta,
    dominantColor: llmBrief.dominant_color || "purple",
    discountBadge: Boolean(winnerData.has_discount_badge),
  };

  const fields: BriefField[] = [
    { label: "Headline", value: brief.headline },
    { label: "Subhead", value: brief.subhead },
    { label: "CTA", value: brief.cta },
    { label: "Dominant color", value: brief.dominantColor },
    { label: "Emotional tone", value: llmBrief.emotional_tone || "urgent" },
    { label: "Duration (s)", value: String(winnerData.duration_sec ?? 15) },
    { label: "Text density", value: String(winnerData.text_density ?? 0.2) },
    { label: "Clutter target", value: "keep low" },
    {
      label: "Discount badge",
      value: brief.discountBadge ? "yes" : "no",
    },
    {
      label: "UGC style",
      value: winnerData.has_ugc_style ? "yes" : "no",
    },
  ];

  const rationale = llmBrief.rationale;

  const lift: LiftRow[] = [
    {
      label: "CTR",
      base: (sourceData.last_7d_ctr as number) ?? (sourceData.overall_ctr as number) ?? 0,
      projected: (winnerData.overall_ctr as number) ?? 0,
      format: "pct",
    },
    {
      label: "CVR",
      base: (sourceData.last_7d_cvr as number) ?? (sourceData.overall_cvr as number) ?? 0,
      projected: (winnerData.overall_cvr as number) ?? 0,
      format: "pct",
    },
    {
      label: "ROAS",
      base: (sourceData.overall_roas as number) ?? 0,
      projected: (winnerData.overall_roas as number) ?? 0,
      format: "roas",
    },
  ];

  return (
    <section
      className="col gap-5"
      style={{ paddingTop: 16, maxWidth: 1100, margin: "0 auto" }}
    >
      <header className="row between center" style={{ flexWrap: "wrap", gap: 12 }}>
        <div className="col gap-1">
          <div className="row center gap-3">
            <Link href={`/creatives/${id}/twin`} className="btn dense">
              ← Back to twin
            </Link>
            <span className="filter-chip mono">V-{id.toString().padStart(6, "0")}-001</span>
            {llmBrief.is_stub ? <PreviewChip /> : null}
          </div>
          <h1 className="t-page" style={{ margin: 0 }}>
            New variant · {llmBrief.segment.vertical} / {llmBrief.segment.format}
          </h1>
          <p className="t-body muted">
            Generated by Gemma 4 from the cohort leader's winning attributes,
            in {String(sourceData.advertiser_name ?? "the source advertiser")}'s voice.
          </p>
        </div>
      </header>

      <ApplyVariantBar
        creativeId={id}
        rationale={`Adopt ${llmBrief.segment.vertical}/${llmBrief.segment.format} cohort leader's attributes`}
      />

      <Lineage fatiguedId={llmBrief.creative_id} winnerId={llmBrief.winner_id} />

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "380px 1fr",
          gap: 20,
          alignItems: "start",
        }}
      >
        <div
          className="col gap-2"
          style={{
            background: "var(--bg-1)",
            border: "1px solid var(--line)",
            borderRadius: 12,
            padding: 14,
            boxShadow: "var(--shadow-1)",
          }}
        >
          <RenderedVariantSvg brief={brief} />
          <span className="t-micro muted" style={{ textAlign: "center" }}>
            Live preview · {llmBrief.is_stub ? "template fallback" : "powered by Gemma 4"}
          </span>
        </div>
        <BriefPanel fields={fields} rationale={rationale} />
      </div>

      <PredictedLift rows={lift} />
    </section>
  );
}
